services:
  ml-api:
    build:
      context: .
      dockerfile: ./ml/Dockerfile
    container_name: evalai-ml-api
    ports:
      - "7860:7860"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./ml/eval_pipe/graded_results:/app/ml/eval_pipe/graded_results
    restart: unless-stopped
